
use std::error::Error;



pub fn main(_args: Vec<String>) -> Result<(), Box<dyn Error>> {
    println!("Error");
    Ok(())
}


